CREATE DATABASE STAGE_1_DB

CREATE DATABASE STAGE_2_DB

CREATE DATABASE DWH_1

CREATE DATABASE CONST_INFO

USE  CONST_INFO
GO

CREATE SCHEMA EMPLOYEE_INFO;


CREATE TABLE [CONST_INFO].[EMPLOYEE_INFO].[EMPLOYEE_ID](

    ID int IDENTITY(1,1),
    Full_name varchar(500),
    EmployeeID varchar(500),
    Last_name varchar(500),
    First_name varchar(500),
    Middle_name varchar(500),
    Note text
)

USE STAGE_1_DB 
GO

Drop table [EMPLOYEE_INFO].[EMPLOYEE_ID]

CREATE SCHEMA BOOKING_SCH_1

CREATE TABLE 

SELECT * FROM [EMPLOYEE_INFO].[EMPLOYEE_ID]


TRUNCATE TABLE [EMPLOYEE_INFO].[EMPLOYEE_ID]

SELECT * FROM [EMPLOYEE_INFO].[EMPLOYEE_ID]
WHERE [NOTE] is not NULL